### ISSUE TITLE
Identify direction from Source Node to Destination Node

### ISSUE THREAD

**Issue by aranderia** [ashleydavis/AngularJS-FlowChart#32]
Hi @ashleydavis , 

I was trying to display arrows on the path indicating direction from the source node to destination node. However, I am stuck on this and couldn't figure out the solution. Please let me know if that's possible and how?

Looking forward to your reply.

Thanks!

**Comment by ashleydavis** [comment]
It's certainly possibly. If you add it to the code please submit a pull request and I'll consider merging it.
